### ISSUE TITLE
i can't find Parse Server on the Azure Marketplace

### ISSUE THREAD

**Issue by michael-mansour** [felixrieseberg/parse-server-azure#1]
Hi, 
I try to follow the instructions detailed on the wiki, but i'm stuck on this step:

> Select Parse Server on managed Azure services published by Microsoft.

I'can't find this asset on the Marketplace. 
Can you help me ?
Thanks a lot

**Comment by adrianhall** [comment]
We are in the process of releasing it.  Watch our Twitter account and Azure Blog - we'll be releasing it in the next couple of days.

**Comment by michael-mansour** [comment]
Thanks !

**Comment by adrianhall** [comment]
It's live now - blog post coming within 24 hours.
