### ISSUE TITLE
How to update parse server ?

### ISSUE THREAD

**Issue by michael-mansour** [felixrieseberg/parse-server-azure#11]
How can I update Parse Server/Parse dashboard ?
Thanks

**Comment by mamaso** [comment]
@skynext, you need to update the node modules for parse server and parse dashboard.  Try going into the Azure Portal -> Parse Server -> Web App -> Console and run 'npm update parse-server parse-dashboard'

**Comment by mamaso** [comment]
Closing for now, feel free to reopen if this doesn't resolve your issue

**Comment by sagarscript** [comment]
Hi I have tried this and get an array of error's/warnings here is a dump of them:
Currently using Parse-Server 2.2.23 and Parse-Dashboard 1.0.22
`
D:\home\site\wwwroot
> npm update parse-server parse-dashboard
D:\home\site\wwwroot
npm http GET https://registry.npmjs.org/parse-server
npm http GET https://registry.npmjs.org/parse-dashboard
npm http 304 https://registry.npmjs.org/parse-server
npm http 304 https://registry.npmjs.org/parse-dashboard
npm WARN engine parse-server@2.2.25: wanted: {"node":">=4.5"} (current: {"node":"v0.10.28","npm":"1.4.9"})
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/pg-promise
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/redis
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/pg-promise
npm http 304 https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request/-/request-2.79.0.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.79.0.tgz
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"v0.10.28","npm":"1.4.9"})
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/uuid
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"v0.10.28","npm":"1.4.9"})
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/spex
npm http 304 https://registry.npmjs.org/spex
Traceback (most recent call last):
  File "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 527, in main
    return gyp_main(args)
  File "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 503, in gyp_main
    options.circular_check)
  File "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1867, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 402, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2015'
gypnpm WARN optional dep failed, continuing bcrypt@0.8.7
`

**Comment by mamaso** [comment]
@Dev-AppLogics 

A lot of these warnings are node and npm complaining about version constraints, as the 'node' and 'npm' aliases are pointing to old versions for your scm site.  Can you create an app setting `WEBSITE_NODE_DEFAULT_VERSION` with value `4.6.1` in order to update the node & npm version in your scm site and retry?

If you want to see the available versions they're at `D:\Program Files (x86)\nodejs`

**Comment by michael-mansour** [comment]
@mamaso Hi I have tried this and I get the following error:
`> npm update parse-server parse-dashboard
D:\home\site\wwwroot
npm WARN deprecated mongodb@2.2.10: Please use 2.2.16 or higher due to a regression in updateOne/Many upsertedId return value
node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v46-win32-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.1 and node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: ENOENT: no such file or directory, open 'D:\home\site\wwwroot\node_modules\parse-server\node_modules\bcrypt\undefined'
gyp ERR! stack     at Error (native)
gyp ERR! stack     at Object.fs.openSync (fs.js:549:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:397:15)
gyp ERR! stack     at readCAFile (D:\Program Files (x86)\npm\2.15.9\node_modules\npm\node_modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download (D:\Program Files (x86)\npm\2.15.9\node_modules\npm\node_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at D:\Program Files (x86)\npm\2.15.9\node_modules\npm\node_modules\node-gyp\lib\install.js:185:19
gyp ERR! stack     at D:\Program Files (x86)\npm\2.15.9\node_modules\npm\node_modules\mkdirp\index.js:30:20
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "D:\\Program Files (x86)\\nodejs\\4.6.1\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.9\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\home\\site\\wwwroot\\node_modules\\parse-server\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=D:\\home\\site\\wwwroot\\node_modules\\parse-server\\node_modules\\bcrypt\\lib\\binding"
gyp ERR! cwd D:\home\site\wwwroot\node_modules\parse-server\node_modules\bcrypt
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\home\site\wwwroot\node_modules\parse-server\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=D:\home\site\wwwroot\node_modules\parse-server\node_modules\bcrypt\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\home\site\wwwroot\node_modules\parse-server\node_modules\bcrypt\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.2.9200
node-pre-gyp ERR! command "D:\\Program Files (x86)\\nodejs\\4.6.1\\node.exe" "D:\\home\\site\\wwwroot\\node_modules\\parse-server\\node_modules\\bcrypt\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\home\site\wwwroot\node_modules\parse-server\node_modules\bcrypt
node-pre-gyp ERR! node -v v4.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
npm WARN optional dep failed, continuing bcrypt@1.0.1
`
