### ISSUE TITLE
MongoError: "Encountered exception while executing Javascript. Query root must be specified."

### ISSUE THREAD

**Issue by michael-mansour** [felixrieseberg/parse-server-azure#13]
Hi, 
For several months, I use Parse server azure without problems but since a few hours I'm getting this error:

> 2017-02-01T09:23:51.925Z - Uncaught internal server error. { [MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p]
  name: 'MongoError',
  message: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  _t: 'OKMongoResponse',
  ok: 0,
  code: 2,
  errmsg: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  '$err': 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p' } MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p
    at Function.MongoError.create (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:462:72
    at authenticateStragglers (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:410:16)
    at null.messageHandler (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:444:5)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\parse-server\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:306:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)
2017-02-01T09:23:51.925Z - Error generating response. { [MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p]
  name: 'MongoError',
  message: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  _t: 'OKMongoResponse',
  ok: 0,
  code: 2,
  errmsg: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p',
  '$err': 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: 3a721634-0000-0000-0000-000000000000, Request URI: rntbd://10.100.100.77:14000/apps/f8a35ed9-3dea-410f-a89a-28650ff41381/services/ab284460-dfd9-4fc6-8366-48ae5708818e/partitions/a108a897-4a3c-44f0-aa7d-477d08f77d67/replicas/131193282907353114p' }

Others users encountered the same issue:
https://github.com/ParsePlatform/parse-server/issues/3462
Thanks for you help

**Comment by adrianhall** [comment]
Seems to be being fixed by the DocumentDB team.
