### ISSUE TITLE
How modify cloud and sync with github ?

### ISSUE THREAD

**Issue by Sofianebenabdallah** [felixrieseberg/parse-server-azure#4]
If I install, can I disconnect in the setting ? How get all file in my github folder to synchronise cloud ?

NOTE : scm on Azure don't work on all my website since 3 days...

regards,

**Comment by adrianhall** [comment]
You can use Continuous Deployment.  Download your site and check into github.  Information is here: https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/
